# permissions for end users to edit pachreleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pachrelease-editor-role
rules:
- apiGroups:
  - ops.pachyderm.io
  resources:
  - pachreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.pachyderm.io
  resources:
  - pachreleases/status
  verbs:
  - get
