# permissions for end users to view pachreleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pachrelease-viewer-role
rules:
- apiGroups:
  - ops.pachyderm.io
  resources:
  - pachreleases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ops.pachyderm.io
  resources:
  - pachreleases/status
  verbs:
  - get
